<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'areacode' => '区域代码',
    'contact type' => '联系方式',
    'created time' => '创建时间',
    'description' => '描述',
    'detail' => '内容',
    'international code' => '国际区号',
    'invalid contact' => '无效接触',
    'location' => '处',
    'name' => '名字',
    'primary contact' => '主要联系人',
    'updated time' => '更新时间',
    'user id' => '用户身份',
    'Username' => '用户名',
    'username' => '用户名',
    'password' => '密码',
    'role' => '角色',
    'status' => '身分',
    'This username has already been taken.'=>'该用户名已被占用。',
    'This email address has already been taken.' => '这个电子邮件地址已经被占用。',
    'Please fill out the following fields to signup' => '请填写以下字段上申请',
    'Signup' => '报名',
    'contact_detail' => '电子邮件'
];
